---
deployment:
  tasks:
    - export DEPLOYPATH=/home/lbdaria/public_html/
    - /bin/mkdir -p $DEPLOYPATH/images $DEPLOYPATH/en $DEPLOYPATH/de
    - /bin/cp -f index.html $DEPLOYPATH
    - /bin/cp -f style.css $DEPLOYPATH
    - /bin/cp -f robots.txt $DEPLOYPATH
    - /bin/cp -f sitemap.xml $DEPLOYPATH
    - /bin/cp -rf images/. $DEPLOYPATH/images/
    - /bin/cp -rf en/. $DEPLOYPATH/en/
    - /bin/cp -rf de/. $DEPLOYPATH/de/
